baseURL = "https://bluelockr.github.io"
languageCode = "ko"
title = "bluelockr's blog"
theme = "github-style"
googleAnalytics = "G-NRBPMYGL5R"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Bluelockr"
  description = "*Î∏îÎ°úÍ∑∏ Í∏¥Í∏â ÏàòÏ†ï Ï§ë*"
  github = "bluelockr"
  facebook = ""
  twitter = ""
  linkedin = ""
  instagram = ""
  tumblr = ""
  email = ""
  url = "https://bluelockr.github.com"
  keywords = "blog, google analytics"
  rss = false
  lastmod = true
  favicon = "/images/github.png"
  location = "South Korea"
  userStatusEmoji = "üêº"
  [[params.links]]
    title = "Link"
    href = "https://github.com/bluelockr"
  [[params.links]]
    title = "Link2"
    href = "https://bluelockr.github.io"
    icon = "https://bluelockr.github.io/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
