baseURL = "https://bluelockr.github.io"
languageCode = "ko"
title = "bluelockr's blog"
theme = "github-style"
googleAnalytics = "G-NRBPMYGL5R"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Bluelockr"
  description = "ê³µë¶€í•˜ë©° ì–»ì€ ì§€ì‹ì„ ê¸°ë¡í•˜ëŠ” ë¸”ë¡œê·¸"
  github = ""
  facebook = ""
  twitter = ""
  linkedin = ""
  instagram = ""
  tumblr = ""
  email = ""
  url = "https://bluelockr.github.com"
  keywords = "blog, google analytics"
  rss = false
  lastmod = true
  favicon = "/images/github.png"
  location = "South Korea"
  userStatusEmoji = "ğŸ¼"
  [[params.links]]
    title = "Link"
    href = "https://github.com/bluelockr"
  [[params.links]]
    title = "Link2"
    href = "https://bluelockr.github.io"
    icon = "https://bluelockr.github.io/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
